task :default => :tu

desc "Pruebas unitarias de la clase Calculadora_IG"
task :tu do
  sh "ruby -I. test/tc_Cocinero.rb"
end

desc "Ejecutar solo las pruebas simples"
task :simple do
  sh "ruby -I. test/tc_Cocinero.rb -n /simple/"
end
